Repository CMPUT301W22T31/QRAdventure, pull requests merged in 2022-03, with the labels that each got.

#45 Michelle/firestoretests
  QRAdventure/.idea/misc.xml
  QRAdventure/app/src/androidTest/java/com/example/qradventure/CameraTest.java
  QRAdventure/app/src/main/AndroidManifest.xml
  QRAdventure/app/src/main/java/com/example/qradventure/Account.java
  QRAdventure/app/src/main/java/com/example/qradventure/AccountActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/Comment.java
  QRAdventure/app/src/main/java/com/example/qradventure/CurrentAccount.java
  QRAdventure/app/src/main/java/com/example/qradventure/EditInfoActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/LoginActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MainActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/PostScanActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/QR.java
  QRAdventure/app/src/main/java/com/example/qradventure/Record.java
  QRAdventure/app/src/main/java/com/example/qradventure/ScanActivity.java
  QRAdventure/app/src/main/res/layout/activity_account.xml
  QRAdventure/app/src/main/res/layout/activity_login.xml
  QRAdventure/app/src/main/res/layout/activity_main.xml
  QRAdventure/app/src/main/res/values/strings.xml
  QRAdventure/app/src/test/java/com/example/qradventure/QRTest.java
Labels: database

#57 Tyler/search username to Staging
  QRAdventure/app/src/main/java/com/example/qradventure/ProfileActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/QRPageActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/SearchPlayersActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/ViewCodesActivity.java
  QRAdventure/app/src/main/res/layout/activity_profile.xml
  QRAdventure/app/src/main/res/layout/activity_search_players.xml
  QRAdventure/app/src/main/res/layout/username_list.xml
  QRAdventure/app/src/main/res/values/strings.xml
Labels: US 05 Searching

#58 Michelle/comments
  QRAdventure/.idea/misc.xml
  QRAdventure/app/src/main/java/com/example/qradventure/Comment.java
  QRAdventure/app/src/main/java/com/example/qradventure/CommentList.java
  QRAdventure/app/src/main/java/com/example/qradventure/CommentsActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MyCodesActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/PostScanActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/QRPageActivity.java
  QRAdventure/app/src/main/res/layout/activity_comments.xml
  QRAdventure/app/src/main/res/layout/activity_my_codes.xml
  QRAdventure/app/src/main/res/layout/activity_qrpage.xml
  QRAdventure/app/src/main/res/layout/content_comment.xml
Labels: US 02 Game QR Codes

#67 Michelle/docs
  QRAdventure/app/src/main/java/com/example/qradventure/Account.java
  QRAdventure/app/src/main/java/com/example/qradventure/AccountActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/AccountFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/Comment.java
  QRAdventure/app/src/main/java/com/example/qradventure/CommentList.java
  QRAdventure/app/src/main/java/com/example/qradventure/CommentsActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/CurrentAccount.java
  QRAdventure/app/src/main/java/com/example/qradventure/EditInfoActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/LeaderboardActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/LeaderboardFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/LocationFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/LoginActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/LoginQRActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MainActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MainFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/MapActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MyCodesActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/MyCodesFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/MyStatsActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/PhotoActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/PlayerPreview.java
  QRAdventure/app/src/main/java/com/example/qradventure/PostScanActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/ProfileActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/QR.java
  QRAdventure/app/src/main/java/com/example/qradventure/QRListAdapter.java
  QRAdventure/app/src/main/java/com/example/qradventure/QRListViewHolder.java
  QRAdventure/app/src/main/java/com/example/qradventure/QRPageActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/QueryCallback.java
  QRAdventure/app/src/main/java/com/example/qradventure/QueryHandler.java
  QRAdventure/app/src/main/java/com/example/qradventure/Record.java
  QRAdventure/app/src/main/java/com/example/qradventure/ScannedByActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/SearchPlayersActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/SearchPlayersFragment.java
  QRAdventure/app/src/main/java/com/example/qradventure/StatusQRActivity.java
  QRAdventure/app/src/main/java/com/example/qradventure/ViewCodesActivity.java
Labels: documentation
